# -*- encoding: utf-8 -*-

=begin
#Rasa - Server Endpoints

#The Rasa server provides endpoints to retrieve trackers of conversations as well as endpoints to modify them. Additionally, endpoints for training and testing models are provided.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

$:.push File.expand_path("../lib", __FILE__)
require "rasa-http-api/version"

Gem::Specification.new do |s|
  s.name        = "rasa-http-api"
  s.version     = Rasa::HTTP::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Daniel Schnell"]
  s.email       = ["dschnell@grammatek.com"]
  s.homepage    = "https://github.com/grammatek/rasa-http-api"
  s.summary     = "A Ruby wrapper for the Rasa HTTP REST API"
  s.description = "This is a Ruby Gem for Rasa HTTP API"
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.4"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
