=begin
#Rasa - Server Endpoints

#The Rasa server provides endpoints to retrieve trackers of conversations as well as endpoints to modify them. Additionally, endpoints for training and testing models are provided.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Rasa::HTTP::DomainApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DomainApi' do
  before do
    # run before each test
    @api_instance = Rasa::HTTP::DomainApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DomainApi' do
    it 'should create an instance of DomainApi' do
      expect(@api_instance).to be_instance_of(Rasa::HTTP::DomainApi)
    end
  end

  # unit tests for get_domain
  # Retrieve the loaded domain
  # Returns the domain specification the currently loaded model is using.
  # @param [Hash] opts the optional parameters
  # @return [Domain]
  describe 'get_domain test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
