=begin
#Rasa - Server Endpoints

#The Rasa server provides endpoints to retrieve trackers of conversations as well as endpoints to modify them. Additionally, endpoints for training and testing models are provided.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Rasa::HTTP::ServerInformationApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ServerInformationApi' do
  before do
    # run before each test
    @api_instance = Rasa::HTTP::ServerInformationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ServerInformationApi' do
    it 'should create an instance of ServerInformationApi' do
      expect(@api_instance).to be_instance_of(Rasa::HTTP::ServerInformationApi)
    end
  end

  # unit tests for get_health
  # Health endpoint of Rasa Server
  # This URL can be used as an endpoint to run health checks against. When the server is running this will return 200.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'get_health test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_status
  # Status of the Rasa server
  # Information about the server and the currently loaded Rasa model.
  # @param [Hash] opts the optional parameters
  # @return [GetStatus200Response]
  describe 'get_status test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_version
  # Version of Rasa
  # Returns the version of Rasa.
  # @param [Hash] opts the optional parameters
  # @return [GetVersion200Response]
  describe 'get_version test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
