=begin
#Rasa - Server Endpoints

#The Rasa server provides endpoints to retrieve trackers of conversations as well as endpoints to modify them. Additionally, endpoints for training and testing models are provided.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'date'
require 'time'

module Rasa::HTTP
  # Conversation tracker which stores the conversation state.
  class Tracker
    # ID of the conversation
    attr_accessor :conversation_id

    # Slot values
    attr_accessor :slots

    attr_accessor :latest_message

    # Most recent event time
    attr_accessor :latest_event_time

    # Deterministic scheduled next action
    attr_accessor :followup_action

    # Bot is paused
    attr_accessor :paused

    attr_accessor :events

    # Communication channel
    attr_accessor :latest_input_channel

    # Name of last bot action
    attr_accessor :latest_action_name

    attr_accessor :latest_action

    attr_accessor :active_loop

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'conversation_id' => :'conversation_id',
        :'slots' => :'slots',
        :'latest_message' => :'latest_message',
        :'latest_event_time' => :'latest_event_time',
        :'followup_action' => :'followup_action',
        :'paused' => :'paused',
        :'events' => :'events',
        :'latest_input_channel' => :'latest_input_channel',
        :'latest_action_name' => :'latest_action_name',
        :'latest_action' => :'latest_action',
        :'active_loop' => :'active_loop'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'conversation_id' => :'String',
        :'slots' => :'Array<Hash>',
        :'latest_message' => :'ParseResult',
        :'latest_event_time' => :'Float',
        :'followup_action' => :'String',
        :'paused' => :'Boolean',
        :'events' => :'Array<Event>',
        :'latest_input_channel' => :'String',
        :'latest_action_name' => :'String',
        :'latest_action' => :'LatestAction',
        :'active_loop' => :'TrackerActiveLoop'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Rasa::HTTP::Tracker` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Rasa::HTTP::Tracker`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'conversation_id')
        self.conversation_id = attributes[:'conversation_id']
      end

      if attributes.key?(:'slots')
        if (value = attributes[:'slots']).is_a?(Array)
          self.slots = value
        end
      end

      if attributes.key?(:'latest_message')
        self.latest_message = attributes[:'latest_message']
      end

      if attributes.key?(:'latest_event_time')
        self.latest_event_time = attributes[:'latest_event_time']
      end

      if attributes.key?(:'followup_action')
        self.followup_action = attributes[:'followup_action']
      end

      if attributes.key?(:'paused')
        self.paused = attributes[:'paused']
      end

      if attributes.key?(:'events')
        if (value = attributes[:'events']).is_a?(Array)
          self.events = value
        end
      end

      if attributes.key?(:'latest_input_channel')
        self.latest_input_channel = attributes[:'latest_input_channel']
      end

      if attributes.key?(:'latest_action_name')
        self.latest_action_name = attributes[:'latest_action_name']
      end

      if attributes.key?(:'latest_action')
        self.latest_action = attributes[:'latest_action']
      end

      if attributes.key?(:'active_loop')
        self.active_loop = attributes[:'active_loop']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          conversation_id == o.conversation_id &&
          slots == o.slots &&
          latest_message == o.latest_message &&
          latest_event_time == o.latest_event_time &&
          followup_action == o.followup_action &&
          paused == o.paused &&
          events == o.events &&
          latest_input_channel == o.latest_input_channel &&
          latest_action_name == o.latest_action_name &&
          latest_action == o.latest_action &&
          active_loop == o.active_loop
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [conversation_id, slots, latest_message, latest_event_time, followup_action, paused, events, latest_input_channel, latest_action_name, latest_action, active_loop].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Rasa::HTTP.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
