=begin
#Rasa - Server Endpoints

#The Rasa server provides endpoints to retrieve trackers of conversations as well as endpoints to modify them. Additionally, endpoints for training and testing models are provided.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Rasa::HTTP::ExecuteConversationAction200Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Rasa::HTTP::ExecuteConversationAction200Response do
  let(:instance) { Rasa::HTTP::ExecuteConversationAction200Response.new }

  describe 'test an instance of ExecuteConversationAction200Response' do
    it 'should create an instance of ExecuteConversationAction200Response' do
      expect(instance).to be_instance_of(Rasa::HTTP::ExecuteConversationAction200Response)
    end
  end
  describe 'test attribute "tracker"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "messages"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
