=begin
#Rasa - Server Endpoints

#The Rasa server provides endpoints to retrieve trackers of conversations as well as endpoints to modify them. Additionally, endpoints for training and testing models are provided.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Rasa::HTTP::IntentDescriptionValue
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Rasa::HTTP::IntentDescriptionValue do
  let(:instance) { Rasa::HTTP::IntentDescriptionValue.new }

  describe 'test an instance of IntentDescriptionValue' do
    it 'should create an instance of IntentDescriptionValue' do
      expect(instance).to be_instance_of(Rasa::HTTP::IntentDescriptionValue)
    end
  end
  describe 'test attribute "use_entities"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
